config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index'
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :players, only: [:new, :create, :show]
  resources :teams, only: [:new, :create, :show] do
    resources :my_players, only: [:index, :new, :create, :show]
  end
  resource :dashboard, only: [:show]
end

app/models/draftee.rb
class Draftee < ActiveRecord::Base
  require 'csv'
  belongs_to :team

  def self.read_file
    CSV.foreach('lib/assets/players.csv', headers: true)  do |row|
      Draftee.create!(row.to_hash)
    end
  end
end

app/models/my_player.rb
class MyPlayer < ActiveRecord::Base
  belongs_to :team
end

app/models/player.rb
class Player < ActiveRecord::Base
  require 'csv'

  def self.read_file
    CSV.foreach('lib/assets/players.csv', headers: true)  do |row|
      Player.create!(row.to_hash)
    end
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :user
  has_many :my_players
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :teams
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Monban::ControllerHelpers
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @team = Team.new
    @teams = current_user.teams
  end
end

app/controllers/my_players_controller.rb
class MyPlayersController < ApplicationController

  def index
    @my_players = MyPlayer.all
  end

  def show
    @my_player = MyPlayer.find(params[:id])
  end

  def create
    team = current_user.teams.find(params[:team_id])
    my_player = team.my_players.create(my_player_params)
    redirect_to team
  end

  private

  def my_player_params
    params.require(:my_player).permit(
      :rank,
      :name,
      :completions,
      :passing_yards,
      :passing_touchdowns,
      :interceptions,
      :rushes,
      :rushing_yards,
      :rushing_touchdowns,
      :receptions,
      :receiving_yards,
      :receiving_touchdowns,
      :points
    ).merge(user_id: current_user.id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def new
    @team = current_user.team.new
  end

  def show
    @team = current_user.teams.find(params[:id])
    @my_players = @team.my_players
    @player = Player.read_file
    @players = Player.all
  end

  def create
    team = Team.create(team_params)
    redirect_to dashboard_path
  end

  private

  def team_params
    params.require(:team).permit(:name).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/show.html.erb
<h2><%= current_user.email %></h2>
<p>
<%= form_for(@team) do |form| %>
  <%= form.label :name, "Team Name" %>
  <%= form.text_field :name %>
  <%= form.submit "Submit" %>
  <p>
<% end %>

<% @teams.each do |team| %>
  <%= link_to team.name, team %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MemeinFreeman</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if signed_in? %>
  <h4><%= link_to "Sign out", session_path, method: :delete %></h4>
<% else %>
  <%= link_to "Sign in", new_session_path %>
  <%= link_to "Sign up", new_user_path %>
<% end %>
<p>

<%= yield %>

</body>
</html>

app/views/my_players/index.html.erb
Sure would be nice if something were here :(
<% @my_players.each do |player| %>
  <%= player.name %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |form| %>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/welcomes/index.html.erb
<% if signed_in? %>
  You are currently signed in.  Click below to enter.
  <p>
  <%= link_to(image_tag('logo.jpg'), dashboard_path) %>
<% else %>
  <%= image_tag('logo.jpg') %>
<% end %>